#!/bin/sh

echo "---------------------------------"
echo "Setting PACKAGE_DIRS to $PACKAGE_DIRS so Meteor can find this package"
echo "---------------------------------"
export PACKAGE_DIRS="$(dirname "$(pwd)")/"

echo "---------------------------------"
echo "Starting code linting in watch mode"
echo "---------------------------------"

npm run lint:watch &

echo "---------------------------------"
echo "Starting demo Meteor application"
echo "---------------------------------"
cd ./demo &&  meteor
